spring.application.name=chat-backend

# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# DATABASE (POSTGRES via Render)
# ===============================
spring.datasource.url=jdbc:postgresql://chatuser:YJu5ylwbD8yn0Oc88vnrHYGBjMlXGtgg@dpg-d5a05i95pdvs73alme20-a/chatdb_mfoz
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
